global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  # Saga Orchestrator metrics
  - job_name: 'saga-orchestrator'
    static_configs:
      - targets: ['saga-orchestrator:8008']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Kong Gateway metrics
  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['api-gateway:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']